/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Index from "./Index"
import plate from "./prefab/plate"
import Level1Main from "./scence/levels/Level1Main"
import LoadingRT from "./LoadingRT"
import StartMain from "./scence/startScene/StartMain"
import CloseBtn from "./prefab/CloseBtn"
import D3Main from "./scence/d3Demo/D3Main"
import PhysicsGameMainRT from "./scence/physicsDemo/PhysicsGameMainRT"
import PhysicsGameMain from "./scence/physicsDemo/PhysicsGameMain"
import DialogRT from "./scence/uiDemo/DialogRT"
import MsgRT from "./scence/uiDemo/MsgRT"
import UiMainRT from "./scence/uiDemo/UiMainRT"
import BagListRT from "./scence/uiDemo/list/BagListRT"
import MailListRT from "./scence/uiDemo/list/MailListRT"
import RefreshRT from "./scence/uiDemo/list/RefreshRT"
import LoopListRT from "./scence/uiDemo/list/LoopListRT"
import ComboBoxRT from "./scence/uiDemo/list/ComboBoxRT"
import TreeListRT from "./scence/uiDemo/list/TreeListRT"
import ProgressRT from "./scence/uiDemo/useUI/ProgressRT"
import TextShowRT from "./scence/uiDemo/useUI/TextShowRT"
import ChangeTextureRT from "./scence/uiDemo/useUI/ChangeTextureRT"
import MouseThroughRT from "./scence/uiDemo/useUI/MouseThroughRT"
import PhysicalCollisionRT from "./scence/uiDemo/useUI/PhysicalCollisionRT"
import MaskRT from "./scence/uiDemo/useUI/MaskRT"
import UsePanelRT from "./scence/uiDemo/page/UsePanelRT"
import IframeElementRT from "./scence/uiDemo/page/IframeElementRT"
import AtlasAniRT from "./scence/uiDemo/animation/AtlasAniRT"
import FrameAniRT from "./scence/uiDemo/animation/FrameAniRT"
import ShapeDetectionRT from "./scence/uiDemo/interactive/ShapeDetectionRT"
import SkeletonAni from "./scence/uiDemo/animation/SkeletonAni"
import Role from "./prefab/Role"
import Folded from "./script/tween/Folded"
import Joystick from "./script/mouse/Joystick"
import DragAndTips from "./script/mouse/DragAndTips"
import ShapeDetection from "./scence/uiDemo/interactive/ShapeDetection"
import ItemBox from "./runtime/box/dataSource/ItemBox"
import OpenMainScene from "./scence/uiDemo/page/OpenMainScene"
import OpenScene from "./scence/uiDemo/page/OpenScene"
import BgImg from "./script/mouse/BgImg"
import Bullet from "./prefab/Bullet"
import DropBox from "./prefab/DropBox"
import LoopImg from "./prefab/LoopImg"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="center";
    static startScene:any="Loading.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=true;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Index.ts",Index);
        reg("prefab/plate.ts",plate);
        reg("scence/levels/Level1Main.ts",Level1Main);
        reg("LoadingRT.ts",LoadingRT);
        reg("scence/startScene/StartMain.ts",StartMain);
        reg("prefab/CloseBtn.ts",CloseBtn);
        reg("scence/d3Demo/D3Main.ts",D3Main);
        reg("scence/physicsDemo/PhysicsGameMainRT.ts",PhysicsGameMainRT);
        reg("scence/physicsDemo/PhysicsGameMain.ts",PhysicsGameMain);
        reg("scence/uiDemo/DialogRT.ts",DialogRT);
        reg("scence/uiDemo/MsgRT.ts",MsgRT);
        reg("scence/uiDemo/UiMainRT.ts",UiMainRT);
        reg("scence/uiDemo/list/BagListRT.ts",BagListRT);
        reg("scence/uiDemo/list/MailListRT.ts",MailListRT);
        reg("scence/uiDemo/list/RefreshRT.ts",RefreshRT);
        reg("scence/uiDemo/list/LoopListRT.ts",LoopListRT);
        reg("scence/uiDemo/list/ComboBoxRT.ts",ComboBoxRT);
        reg("scence/uiDemo/list/TreeListRT.ts",TreeListRT);
        reg("scence/uiDemo/useUI/ProgressRT.ts",ProgressRT);
        reg("scence/uiDemo/useUI/TextShowRT.ts",TextShowRT);
        reg("scence/uiDemo/useUI/ChangeTextureRT.ts",ChangeTextureRT);
        reg("scence/uiDemo/useUI/MouseThroughRT.ts",MouseThroughRT);
        reg("scence/uiDemo/useUI/PhysicalCollisionRT.ts",PhysicalCollisionRT);
        reg("scence/uiDemo/useUI/MaskRT.ts",MaskRT);
        reg("scence/uiDemo/page/UsePanelRT.ts",UsePanelRT);
        reg("scence/uiDemo/page/IframeElementRT.ts",IframeElementRT);
        reg("scence/uiDemo/animation/AtlasAniRT.ts",AtlasAniRT);
        reg("scence/uiDemo/animation/FrameAniRT.ts",FrameAniRT);
        reg("scence/uiDemo/interactive/ShapeDetectionRT.ts",ShapeDetectionRT);
        reg("scence/uiDemo/animation/SkeletonAni.ts",SkeletonAni);
        reg("prefab/Role.ts",Role);
        reg("script/tween/Folded.ts",Folded);
        reg("script/mouse/Joystick.ts",Joystick);
        reg("script/mouse/DragAndTips.ts",DragAndTips);
        reg("scence/uiDemo/interactive/ShapeDetection.ts",ShapeDetection);
        reg("runtime/box/dataSource/ItemBox.ts",ItemBox);
        reg("scence/uiDemo/page/OpenMainScene.ts",OpenMainScene);
        reg("scence/uiDemo/page/OpenScene.ts",OpenScene);
        reg("script/mouse/BgImg.ts",BgImg);
        reg("prefab/Bullet.ts",Bullet);
        reg("prefab/DropBox.ts",DropBox);
        reg("prefab/LoopImg.ts",LoopImg);
    }
}
GameConfig.init();